FROM --platform=$BUILDPLATFORM golang:1.25-alpine3.21 AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /app
COPY tg-filestreambot/ .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /app/fsb -ldflags="-w -s" ./cmd/fsb

FROM alpine:3.21
RUN apk --no-cache add ca-certificates tzdata
COPY --from=builder /app/fsb /app/fsb
COPY stream-bot/fsb.env /app/fsb.env
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/app/fsb", "run"]
